elm327:
  mac: "XX:XX:XX:XX:XX:XX"
mqtt:
  broker: "mqtt.example.com:1883"
  # username: "user"  # Опционально: закомментируйте или удалите для анонимного подключения
  # password: "pass"  # Опционально: закомментируйте или удалите для анонимного подключения
  data_topic: "elm327/data"
  command_topic: "elm327/command"
logging:
  level: "info"  # Установите в "debug" для детального логирования MQTT команд и ответов Bluetooth