version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

  app:
    build: .
    container_name: car-diag-app
    depends_on:
      - mosquitto
    volumes:
      - .:/app
    privileged: true
    devices:
      - /dev:/dev
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log: