name: Go CI/CD for Pi-Bridge

on:
  push:
    branches: [ main ]
    paths:
      - 'pi-bridge/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./pi-bridge
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.1'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...

    - name: Build for Raspberry Pi
      run: GOOS=linux GOARCH=arm64 go build -o elm327-bridge main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: elm327-bridge
        path: pi-bridge/elm327-bridge

  deploy:
    needs: build-and-test
    runs-on: self-hosted
    env:
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: elm327-bridge

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.REMOTE_HOST }}
        username: ${{ env.REMOTE_USER }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        port: 22
        source: "elm327-bridge"
        target: "/home/user/elm327/"